webtalk_init -webtalk_dir C:\\SharedProjects\\Sadias_Directory\\BERT\\project_3\\project_3.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2018-02-02 17:22:29" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2017.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2017.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "174129051_174129052_210622774_362" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "jhv2jtr7sq6co4qaojjjbb6d9s" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2017.2_9" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "9" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 7 , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Service Pack 1  (build 7601)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2294 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1517609822810" -context "sdk\\\\hardware/1517609822810"
webtalk_add_data -client sdk -key isZynq -value "false" -context "sdk\\\\hardware/1517609822810"
webtalk_add_data -client sdk -key isZynqMP -value "false" -context "sdk\\\\hardware/1517609822810"
webtalk_add_data -client sdk -key Processors -value "1" -context "sdk\\\\hardware/1517609822810"
webtalk_add_data -client sdk -key VivadoVersion -value "2017.2" -context "sdk\\\\hardware/1517609822810"
webtalk_add_data -client sdk -key Arch -value "virtex7" -context "sdk\\\\hardware/1517609822810"
webtalk_add_data -client sdk -key Device -value "7vx485t" -context "sdk\\\\hardware/1517609822810"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1517609822810"
webtalk_add_data -client sdk -key os -value "NA" -context "sdk\\\\hardware/1517609822810"
webtalk_add_data -client sdk -key apptemplate -value "NA" -context "sdk\\\\hardware/1517609822810"
webtalk_add_data -client sdk -key RecordType -value "HWCreation" -context "sdk\\\\hardware/1517609822810"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1517613749418"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1517613749418"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1517613749418"
webtalk_add_data -client sdk -key DebugCount -value "6" -context "sdk\\\\bsp/1517613749418"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1517613749418"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1517613749418"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1517613749418"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1517613749418"
webtalk_transmit -clientid 543886317 -regid "174129051_174129052_210622774_362" -xml C:\\SharedProjects\\Sadias_Directory\\BERT\\project_3\\project_3.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html C:\\SharedProjects\\Sadias_Directory\\BERT\\project_3\\project_3.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm C:\\SharedProjects\\Sadias_Directory\\BERT\\project_3\\project_3.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
