set_property SRC_FILE_INFO {cfile:C:/SharedProjects/Sadias_Directory/BERT/project_3/project_3.srcs/constrs_1/new/constraints.xdc rfile:../../../project_3.srcs/constrs_1/new/constraints.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F40 [get_ports {out_p[0]}]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V30 [get_ports in_p]
